### PR TITLE
Version 1.0.7

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by lundibundi** [comment]
Can we also include https://github.com/metarhia/impress/pull/1154 in this release?

**Comment by tshemsedinov** [comment]
@lundibundi https://github.com/metarhia/impress/pull/1154 and https://github.com/metarhia/impress/pull/1163 included

**Comment by tshemsedinov** [comment]
Is it ready to include https://github.com/metarhia/impress/pull/1157 @lundibundi  ?

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/impress/commit/4b9b7192b741cf14ae94479e8b113c8cec658269

**Pull request closed without merging**
