### PR TITLE
Fix graceful shutdown

### PR DESCRIPTION
**Pull request by tshemsedinov**
This may fix https://github.com/metarhia/impress/issues/1165

### CODE REVIEW

**Comment by lundibundi** [comment]
Not sure how, but this seems to lead to impress worker not finishing while it has at least one JSTP connection active.

**Comment by tshemsedinov** [comment]
@lundibundi try now, I added `'stopping'` event and graceful shutdown timeout. If `server.close` will not call callback after timeout, we will emit `'stopped'` and `exit(0)`

**Comment by tshemsedinov** [comment]
@lundibundi I'll refactor this and `ready` event using this abstraction https://github.com/metarhia/metasync/pull/427 after publishing `AsyncEventEmitter` in metasync

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/impress/commit/c6c69be36db4e45fb84151fe1e9a5dec28692c76

**Pull request closed without merging**
