### PR TITLE
Publish version 0.3.39

### PR DESCRIPTION
**Pull request by tshemsedinov**
May we also update following dependencies?
- MetaSync from `0.0.x` to `0.2.x`
- JSTP `0.5.x` to `0.6.x`
- GlobalStorege from `0.0.x` to `0.1.x`
@aqrln @belochub

### CODE REVIEW

**Comment by aqrln** [comment]
> JSTP 0.5.x to 0.6.x

Nope, it breaks compatibility with Node.js 4.x. We still maintain it specially for Impress 0.3.

**Comment by tshemsedinov** [comment]
@aqrln @belochub so publishing with just 'uglify-js' updated and version increment. Approve plz

**Comment by tshemsedinov** [comment]
@aqrln #723 done

**Comment by tshemsedinov** [comment]
Landed in 81e638f0aa51ada0fcf2b529af22b0c391a0fd64

**Pull request closed without merging**
