### PR TITLE
Version 1.0.0-alpha.8

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by lundibundi** [comment]
Perhaps we should also run `npm update`?

Also, could you check the changes to package-lock.json as for some reason `fsevents` got removed while nothing in the `package.json` updated.

**Comment by tshemsedinov** [comment]
@lundibundi I have executed `npm update` and `npm dedupe` and it removed `fsevents`

**Comment by tshemsedinov** [comment]
Landed in cbb2426

**Comment by tshemsedinov** [comment]
@lundibundi `fsevents` was dependency of `chokidar` but now `chokidar` doesn't depend on it. I don't know why npm didn't removed it before

**Pull request closed without merging**
