### PR TITLE
Change nodejs version in deploy scripts to 9.x

### PR DESCRIPTION
**Pull request by o-rumiantsev**
But haven't tested on virtual machine.

### CODE REVIEW

**Comment by tshemsedinov** [comment]
Oh, I missed the comment. Please test it with CentOS and Fedora (at least) before merge, I think we may have problems with deploy.

**Comment by o-rumiantsev** [comment]
Fedora 27:
`Impress Application Server CLI

Error: Command failed: sudo ./bin/install.sh
Synchronizing state of impress.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable impress
Created symlink /etc/systemd/system/multi-user.target.wants/impress.service → /etc/systemd/system/impress.service.`

CentOS 7:
`Impress Application Server CLI

Error: Command failed: sudo ./bin/install.sh
Created symlink from /etc/systemd/system/multi-user.target.wants/impress.service to /etc/systemd/system/impress.service.`

Debian 7:
`E: Unable to locate package nodejs
sudo: npm: command not found
sudo: npm: command not found`

Ubuntu, Debian9 - OK
CentOS - FAILED

**Comment by o-rumiantsev** [comment]
Failed in CentOS 6

**Comment by tshemsedinov** [comment]
We can deprecate support for CentOS 6 and Ubuntu
@belochub @nechaido please help @o-rumiantsev to fix this

**Comment by o-rumiantsev** [comment]
It's everything ok with Ubuntu, maybe you meant Debiant 7?

**Comment by nechaido** [comment]
@o-rumiantsev this should be rebased on master.

**Comment by tshemsedinov** [comment]
@nechaido ping

**Comment by nechaido** [comment]
At the moment we don't know why Fedora and CentOS 7 installation fail, it is likely to be caused by: https://github.com/metarhia/impress-cli/issues/25, but we don't know yet.

**Comment by nechaido** [comment]
We should add `dnf install -y gcc-c++` to fedora installation scripts.

**Comment by nechaido** [comment]
@o-rumiantsev please check installation on Fedora 27, Debian 7, Debian 8, CentOS 7.

**Comment by o-rumiantsev** [comment]
All tests are done. No errors got

**Comment by nechaido** [comment]
@o-rumiantsev please squash commits and rename resulting commit into `Change nodejs version in deploy scripts to 9.x`.

**Comment by nechaido** [comment]
Landed in 7b6b841.

**Pull request closed without merging**
